
server:
  port: 8086

# RabbitMQ connection properties
spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: kien
#    password: 123

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:kien}
    password: ${RABBITMQ_PASSWORD:123}