
server:
  port: 8087

# RabbitMQ connection properties
#spring:
#  rabbitmq:
#    host: ${RABBITMQ_HOST:localhost}
#    port: ${RABBITMQ_PORT:5672}
#    username: ${RABBITMQ_USERNAME:kien}
#    password: ${RABBITMQ_PASSWORD:123}

spring:
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: kien
  #    password: 123

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:kien}
    password: ${RABBITMQ_PASSWORD:123}
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    queue:
      picture:
        filter: q.picture.filter
        image: q.picture.image
        vector: q.picture.vector
        log: q.picture.log
      hr:
        accounting: q.hr.accounting
        marketing: q.hr.marketing
      my:
        queue: my-queue
        student: my-student
    exchange:
      x:
        hr: x.hr
        picture: x.picture
        picture2: x.picture2
