version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.12.0-management
    container_name: rabbitmqlearn
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=kien
      - RABBITMQ_DEFAULT_PASS=123